README.md

>We’re thrilled to be participating in this year’s Hacktoberfest. Any contributor who gets three pull requests submitted and merged in any source{d} repo between October 1 and October 31 will receive a limited edition T-shirt as well as one sticker for those who get at least one pull requests merged.
https://medium.com/sourcedtech/celebrating-open-source-with-hacktoberfest-2018-7283cfc6666b

Correct requirements and swag for source{d}

---

README.md

Added Nexmo

---

README.md

Update README to include Magento

---

CONTRIBUTING.md
README.md

 added LBRY to swag list, name to contributors

---

CONTRIBUTING.md

Hi again!
Updated the contribution guidelines to match the reorg I did with the swag list. 😄

feature: update contribution guidelines to match swag list layout

---

CONTRIBUTING.md
README.md

I put the list in alphabetical order, adjusted some formatting, and added Magento's information.

Alphabetical List and Added Magento

---

README.md

Add OpenBazaar to the list

---

_layouts/default.html

Add a disclaimer stating that this site/list is not directly affiliated with any companies sponsoring Hacktoberfest.

Add disclaimer to website

---

_layouts/default.html

In an attempt to Fix #33, this moves the disclaimer to the footer.

Move disclaimer to footer

---

README.md

At the beginning, the text still showed 2019

2018 -> 2019

---

CONTRIBUTING.md
README.md

1. fixed some smol grammatical things :)
2. it's only 4 quality PRs now, not 5.

Made a couple of copyedits.

---

CONTRIBUTING.md
README.md

- **Swag**: T-shirt and Stickers
- **Requirements**:
- 1 - 3 pull requests: Limited-Edition Stickers
- 4+ pull requests: Limited-Edition T-shirt
- **How to sign up**: [Join #Orbtoberfest](https://circleci-public.github.io/hacktoberfest/#/) and submit your PRs to this [Google Form](https://docs.google.com/forms/d/1-MbzLy0m1eRLjeye9wu76fYkzcX5A3PvgKd09EhVObY/viewform).
- **Notes**: View full details above. Make pull requests to any open-source "orbs" for CircleCI, or create your own. When complete submit PRs to the Google form to claim swag.
Here is an image of both swag items: https://circleci-public.github.io/hacktoberfest/img/hacktober19_swag-mockup.6289c5ce.png
Thanks for keeping this awesome list going every year! This is CircleCI's first-ever year participating in Hacktoberfest!

Add CircleCI Swag

---

CONTRIBUTING.md
README.md

Added Appwrite to SWAG list

---

README.md

platform.uno is participating in #hacktoberfest

---

_config.yml

No longer including the old Develop.md file

Remove DEVELOP.md

---

CONTRIBUTING.md
README.md

Les-Tilleuls.coop is the company behind [API Platform](https://api-platform.com/), they announced they'd give away swag to anyone who contributes at least four PRs to their repositories.

Add Les-Tilleuls.coop to companies who contribute to Hacktoberfest.

---

README.md

Added OpenEBS

---

README.md

SalesAgility gives away a mug for each contributor who submitted at
least one merged pull request to one of their mentioned repositories.

Add SalesAgility to swag list.

---

README.md

Add Twilio to swag list.

---

README.md

Added Adobe/Magento in the Swag list.

Add Adobe/Magento to Swag list

---

CONTRIBUTING.md
README.md

Added Accord Project details for Hacktoberfest.
Resolves #55

Added Accord Project

---

CONTRIBUTING.md
README.md

Please leave me a comment if changes are needed

added Gatsby

---

CONTRIBUTING.md
README.md

I'm from this community, and the entry here had a bit of awkward wording that I wanted to cleanup and to add in the contributing guides from the website.
I also seen the Top Contributors section wasn't present in CONTRIBUTING.md but had been added in the past to the README.md, so added that in too for convenience.

Pydis refine

---

README.md

https://github.com/crweiner/hacktoberfest-swag-list/issues/53

Added LBRY to list

---

README.md

Added Sense/Net to Swag list

---

CONTRIBUTING.md
README.md

Added SenseNet

---

README.md

Changed "five one or more" in the requirements for Adobe
Changed "at least one or more" in requirements for Appwrite

Fix some wording to improve clarity

---

README.md

Just found another company. It's LadybugTools. They provide contributors
with stickers! Isn't that amazing?

Add LadybugTools to Hacktoberfest swag list

---

README.md

Update to emphasize you need to sumbit **accepted** PRs to receive swags from Accord Project

Update some description to make it more understandable

---

README.md

Add Devfolio to swag list

---

CONTRIBUTING.md
README.md

MayaData is the correct company name.
OpenEBS is only a project of MayaData on which you can contribute.

Fixed company name from OpenEBS to MayaData

---

CONTRIBUTING.md
README.md

I found another company called QMK, they're giving out t-shirts (as well as a chance to win a keyboard!) for 4 interactions with any of the QMK repos

Added QMK to the list!

---

CONTRIBUTING.md
README.md

* Adds me to the list of contributors
* Fixes formatting
Closes #139

Adds JabRef

---

README.md

Gatsby was added with #113, but the swag is not related to Hacktoberfest.

Removed Gatsby

---

CONTRIBUTING.md
README.md

2 typos corrected to company's

Les-Tilleuls.coop entries

---

CONTRIBUTING.md
README.md

I've tried to uniform, standardize, fix, re-order and simplify pretty much everything.
I could go on forever but had to stop eventually.

Refactor of everything

---

assets/css/style.scss

[WIP]Fix CSS for footer on smaller screens

---

README.md

Add Saleor in both lists and Fix Typo

---

README.md

Added Software Mansion to Swag List

---

README.md

Coding Blocks require at least 1 merged PR to be eligible for a shirt and a sticker pack

Move Coding Blocks to "1 Merged PR" section

---

README.md

Changes occurrences of:
- 'Sing' to 'Sign'
- "PR's" to "PRs" (for consistency.)
- improperly capitalized "Laptop" to "laptop"

Typo fixes in readme.

---

CONTRIBUTING.md

I wanted to update the Contributing rules to add rules on submitting quality PRs and the expectation to quickly correct flagged errors.

Update Contributing rules

---

CONTRIBUTING.md
README.md

Globo.com's entry had the "how to sign up" line duplicated

Remove duplicate line from README.md

---

CONTRIBUTING.md
README.md

added flutterwave.com hacktoberfest announcement

added flutterwave.com

---

README.md

As discussed in #206 this PR adds links to issues for all the companies.

Added links to issues.

---

.circleci/config.yml
Gemfile

Fixes #50.
An example build from my account: https://circleci.com/gh/felicianotech/hacktoberfest-swag-list/9

Add starter CircleCI config.

---

README.md

Jenkins contribution in Hacktoberfest 2019.

Add Jenkins

---

.github/pull_request_template.md
README.md

Really excited to be on the list for our second year of Hacktoberfest 🥳

Added Appwrite :)

---

README.md

Added LoginRadius swags

---

README.md

I've added DX Heroes to this awesome list.

Added DX Heroes

---

CONTRIBUTING.md
README.md

Added Vonage/Nexmo

---

README.md

Added JetBrains

---

README.md

Added Globo

---

CONTRIBUTING.md
README.md

Add MayaData

---

README.md

Added Devfolio

---

README.md

Adding earthly, as mentioned here https://blog.earthly.dev/hacktoberfest-2020/
@crweiner

Adding Earthly

---

CONTRIBUTING.md
README.md

1. [*] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [*] I'm not adding a company from the blocklist
3. [*] I make sure to fix things promptly if an error or suggestion comes up

Add Datenanfragen.de e. V.

---

README.md

Added CircleCI Swag Offer For Hacktoberfest

---

README.md

fixed Devfolio Notes

---

README.md

Added [Appsmith](https://github.com/appsmithorg/appsmith/discussions/863) to the list of repositories

Added Appsmith to the README.md

---

README.md

Fix Typos in Operation Code Entry

---

README.md

As per the [DEV brand guidelines](https://dev.to/brand), it should be spelled out in all caps in this context.

Capitalize DEV :)

---

README.md

Added Hasura

---

README.md

- - - -
Digital Ocean has cracked down on low quality PRs in recent years. On the PR dashboard, there's a warning against ineligible repos.
> **Ineligible Repository**
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add …

Clarifying PR requirements

---

README.md

Added parabeac core

---

README.md

Add Commerce.js

---

README.md

The requirements are a bit misleading at sensenet. I've add some changes to make it more clear :)

Update sensenet's requirements in README

---

CONTRIBUTING.md
README.md

- Added Zup Innovation details to Hacktoberfest-swag-list 🚀  
2. [ ] I'm not adding a company from the blocklist

Add Zup Innovation details to Hacktoberfest-swag-list

---

README.md

Added a updated guidelines article from hacktoberfest official site, to prevent spamming.

updated guidelines article from hacktoberfest official site

---

README.md

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:!

Inconsistency in text size corrected

---

README.md

Added Stack Builders to the list

---

README.md

1. [ ] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Align to Contributing document

---

README.md

Hi, @crweiner. This is just a PR to fix some typos in README.md file. If you feel that this should not be marked as eligible, you can mark this PR as invalid.
Cheers
Checklist:
1. [X] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly

Fix typo in README.MD

---

README.md

I've added Activeloop to README.md

Adding Activeloop to the Swag list

---

CONTRIBUTING.md
README.md

1. [X] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly

Setting links to open in a new tab (I believe this is normal behavior on sites)

---

README.md

Fix some technical issue and typos in README

---

CONTRIBUTING.md
_layouts/default.html

Opens external links in a new tab

---

CONTRIBUTING.md
README.md

Hi everyone! We (@datenanfragen) are in for yet another year. :)
3. [x] I'll make sure to fix things promptly if an error or suggestion comes up

Add Datenanfragen.de to the list

---

CONTRIBUTING.md
README.md

Add pranjal

---

CONTRIBUTING.md
README.md

Add entry for Appwrite

---

README.md

docs: Adds entry for Appsmith

---

CONTRIBUTING.md
README.md

Add AutoDL to list

---

README.md

Closes #401 Add LoginRadius to list

---

README.md

1. [X] I have read the [Contributing.md](../CONTRIBUTING.md) file and formatted this PR correctly

Fix Domain misspelling

---

CONTRIBUTING.md
README.md

Added Earthly to list

---

README.md

Added Bridgecrew to list

---

CONTRIBUTING.md
README.md

mistyped repositories

---

CONTRIBUTING.md
README.md

Add PayPal

---

README.md

Adding ArchivesSpace

---

README.md

Adding Milvus as company

---

CONTRIBUTING.md

Fix dead Hacktoberfest quality standards link

---

CONTRIBUTING.md
README.md

* This is recent PR for #430  which also wraps up the fixes required in #425 *

Native script

---

README.md

loginradius needs 1 merged pr so i shifted it to 1 merged pr section

Changing loginradius position from pr to merged pr

---

CONTRIBUTING.md
README.md

add MayaData to swag list

---

assets/css/style.scss

….. to eliminate overlapping issues on shorter screens

fixes #442 overlapping footer

---

README.md

https://github.com/crweiner/hacktoberfest-swag-list/issues/446
Add Bitrise to the 2021 Hacktoberfest Swag List!

[#446] [README.md] Add Bitrise to the 2021 Hacktoberfest Swag List!

---

docs/list.md

fix: add encore to new mkdocs list

---

docs/list.md

Added Aviyel Swaglist to the Repository

---

docs/list.md

Signed-off-by: Samhita Alla <aallasamhita@gmail.com>
3. [ x I make sure to fix things promptly if an error or suggestion comes up

Add Flyte and UnionML

---

docs/list.md
index.md

1. [X] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/CONTRIBUTING.md) file and formatted this PR correctly

added invertase to the company list

---

docs/list.md

Added Bagisto and devICT

---

docs/list.md

Add Pusher to the Swag List

---

docs/list.md

Add Appwrite to Swag List

---

docs/list.md

Adding Percona to the list. This PR Resolves #552.

Add Percona to the List

---

docs/list.md

Add Hasura to company list.

---

.gitignore
Pipfile
Pipfile.lock
mkdocs.yml

feat: add social cards

---

docs/list.md

1. [ ] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

Added tooljet

---

docs/list.md

1. [ X] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [X ] I'm not adding a company from the blocklist
3. [ X] I make sure to fix things promptly if an error or suggestion comes up

added medusajs to the list

---

docs/index.md
mkdocs.yml

Update mkdocs.yml enables Attributes List

---

docs/list.md

Fix the order.

---

docs/list.md

Add metafy to swaglist for hacktoberfest 2022

---

docs/list.md

Also, all the swag and event details are officially confirmed with the Novu team. This should fix https://github.com/crweiner/hacktoberfest-swag-list/issues/578

Added Novu to the Hacktoberfest 2022 Swag List!

---

docs/list.md

Corrected a spelling mistake!

---

docs/list.md

Add Mattermost to Swag List

---

docs/list.md

Add LocalStack to list.md

---

docs/list.md

Added Space Jelly and Cloudinary to 2022 list
Reference to #601 

Added Space Jelly and Cloudinary to 2022 list

---

docs/list.md

Add Speckle to the List

---

docs/list.md

add amplication

---

docs/list.md

add encore to swag list

---

docs/list.md

closes #610 
This pr adds Steampipe to the swag-list.
1. [✔] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [✔] I'm not adding a company from the blocklist
3. [✔] I make sure to fix things promptly if an error or suggestion comes up

Add Steampie

---

docs/list.md

feat: add Uno hacktoberfest swag listing

---

docs/list.md

Add Dagshub to list.md

---

docs/list.md

Added LambdaTest to list.md

---

docs/list.md

added OpenSearch to the swag list

---

docs/list.md

added RapidAPI

---

docs/list.md

Added Airbyte to the swag list.

---

docs/list.md

feat: add Appsmith Hacktoberfest swag listing

---

docs/list.md

Add Gita To The Hacktoberfest Swag List

---

docs/list.md

Added SuiteCRM(fixed)

---

docs/contributing.md
docs/list.md

feat: addition of Chimoney

---

docs/list.md

Add refine to the company swag list

---

docs/list.md

1. [ ] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [ ] I'm not adding a company from the blocklist
3. [ ] I make sure to fix things promptly if an error or suggestion comes up

feat: added NativeScript to Hacktoberfest swag list

---

docs/list.md

Added Modtoberfest to the Hacktoberfest Swag List. #657

Add Modtoberfest

---

docs/contributing.md
docs/list.md

This PR has a few small fixes and some updates
The  [contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/9f216f38ad9c1861c63d5c50d5dff8d3a6414405/docs/contributing.md) links to a markdown cheatsheet no longer works. I replaced it with a new link
_Old link_ - https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf
**New link** - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
If …

fix: broken links, updates, typos

---

docker-compose.yml
docs/contributing.md

add steps for building site locally

---

docs/list.md

feat: add HackSquad to Hacktoberfest Swag Listing

---

docs/list.md

#641  I have updated heading level for Legend A and F, and items in A and F. 

Heading level change test

---

docs/list.md

As confirmed on [Meilisearch blog](https://blog.meilisearch.com/hacktoberfest-2022-mid-october-update/)

Updated Meilisearch swag with accurate info

---

docs/list.md

Updated a few things in this PR
Updated Pusher to include the revealed items of the swag bag. 
https://twitter.com/pusher/status/1580864210606895104?cxt=HHwWgMDR9fXnrfArAAAA
Updated to include stickers and a sweater instead of a hoodie as swag. 
https://platform.uno/blog/uno-platform-at-hacktoberfest-2022-prizes-and-how-to-participate/
Added the link to the form to claim the swag after successfully contribution. 
Updated some formatting for the labels, changed it from bold to code. 
Thank you
Tagging …

add: atsign, juliaactuary, openmetadata + update: pusher, uno, invertase, encore 

---

docs/list.md

update: add resuminator, appflowy, codédex  and Razorpay to the list

---

docs/list.md

Add Hyperswitch to list.md

---

docs/list.md

adding Flyte to swag list

---

docs/list.md

--- 
This PR includes 
- More participating companies, projects and events. 
- Updated the instructions for *How to sign up* for the entire list based on your last commit.

Added more participants

---

docs/list.md

chore: Added Interledger foundation to swag list

---

docs/list.md

Include Ballerina

---

docs/list.md

Added MLH Global Hack Week to the swag list

---

docs/list.md

add: formbricks

---

docs/list.md

Added Otterize to the Hacktoberfest Swag List

---

docs/list.md

Added Swirl to the Hacktoberfest Swag List 

---

docs/list.md

Added Hanko to the Hacktoberfest Swag List

---

docs/list.md

Add UNO Platform to the Hacktoberfest swag list

---

docs/list.md

Added flutter_deck Hacktoberfest to the Swag List

---

docs/list.md

Add Chimoney to the Hacktoberfest Swag List

---

docs/list.md

Added Bitwarden to the Hacktoberfest Swag List (#741)

---

docs/list.md

Added Collectiv to the Hacktoberfest Swag List (#740)

---

docs/list.md

Add Appsmith (#735)

---

docs/list.md

Added Akto to the Hacktoberfest Swag List (#737)

---

docs/list.md

 Add QuestDB to the Hacktoberfest Swag List (#755) 

---

docs/list.md

Added Weaviate in the list

---

docs/list.md

Fixes #772 
1. [✅] I have read the [Contributing.md](https://github.com/crweiner/hacktoberfest-swag-list/blob/master/docs/contributing.md) file and formatted this PR correctly
2. [✅] I'm not adding a company from the blocklist
3. [✅] I make sure to fix things promptly if an error or suggestion comes up

Added Loft Labs to the lists

---

docs/list.md

Added Configu in the list

---

docs/list.md

Added Covalent to the Hacktoberfest Swag List

---

docs/list.md

Added stackbuilders in the list

---

docs/list.md

Added Featureform in the list

---

docs/list.md

Added Trigger.dev in the list

---

docs/list.md

Added SurrealDb in the list

---

docs/list.md

Added WavePlay in the list.

---

docs/list.md

Added KodaDot in the swags list

---

docs/list.md

added logto in the list

---

docs/list.md

Added ClickVote in the list

---

docs/list.md

Added TBD to list.md

---

docs/list.md

Added Appblocks in the list

---

docs/list.md

Add OVHCloud to Hacktoberfest Swag List

---

docs/list.md

---
This PR adds Hugging Face, Prefix.dev, HaystackAI and Sia Foundation to the list.
It also fixes the heading hierarchy for QuestDB.

Added few more participants

---

docs/list.md

Added Truffle Security in the list

---

docs/list.md

Readded Airbyte

---

docs/list.md

Closes #825 
Keeping it in draft since Quine said they will be adding more details in [this Twitter Thread](https://twitter.com/quine_sh/status/1712081594431782973)

Added Quine to the list

---

docs/list.md

Adding Dyte.io to the list

---

docs/list.md

Added Revert into hacktoberfest swag list issue - #830

---

docs/list.md

Added Zilliz to the list

---

docs/list.md

Added Taipy to the Hacktoberfest Swag List

---

docs/list.md

Added Depths to the Hacktoberfest Swag List
Closes: https://github.com/crweiner/hacktoberfest-swag-list/issues/843

Added Depths to the Hacktoberfest Swag List

---

docs/list.md

Added Vesoft in the list 

---

docs/list.md

Add odigos and wevis

---

docs/list.md

I have added Huddle01 to the list as specified by issue #827 

Added Huddle01 to list.md as per issue #827

---

docs/list.md

Add OpenSign to list.md

---

docs/list.md

Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) :smiley: :tada:! Before submitting your pull request(Fixes #846), please check off as many of the items below as you can:

Add Chainguard to Hacktoberfest Swag List

---

docs/list.md

closes #893 
closes #890 
closes #879

Add auth0, modtoberfest and cloudinary to the list

---

docs/list.md

Add Instill AI to list #882

---

docs/list.md

-> GH post announcing the Langfuse Hacktoberfest swag: https://github.com/langfuse/langfuse-docs/issues/827

Add Langfuse Hacktoberfest 2024 Swag

---

docs/list.md

Include Ballerina information

---

docs/list.md

Update list.md with TBD Hacktoberfest Info

---

docs/list.md

Fix issue #880: updated list.md with tscircuit

---

docs/list.md

Add Flyte to swag list

---

docs/list.md

add LambdaTest to swag list

---

docs/list.md

Added Configu to list.md

---

docs/list.md

add crawlee for python to swag list

---

docs/list.md

See https://community.gradle.org/events/hacktoberfest/2024/ for all the information about the program.

Add Gradle to the Swag list

---

docs/list.md

docs: Add Robo.js to list.md

---

docs/list.md

PR for Issue #908 Add Tolgee to the Hacktoberfest Swag List

Add Tolgee

---

docs/list.md

added composio in list.md file

---

docs/list.md

Add Chimoney

---

docs/list.md

Added Taipy to list.md

---

docs/list.md

added esri in list.md file

---

docs/list.md

Add Opencast and Postiz to Hacktoberfest swag list

---

docs/list.md

Add Asgardeo React SDK to the Hacktoberfest Swag List

---

docs/list.md

fixes #951 (Add Portkey to the Hacktoberfest Swag List)

added portkey to list.md

---

docs/list.md

closes #945 
closes #948 
closes #950 
closes #954 
closes #965

Add Kairos, WrenAI, Razorpay QuickBlok and Airbyte

---

docs/list.md

Fixed issue #957 - Added AntennaPod to list.md

---

netlify.toml

Fixing Netlify's deploy abilities.

Install MkDocs via pip3

---

docs/list.md

docs: Add Questdb to the list.md

---

docs/list.md

docs: Add goose to the list.md

---

docs/list.md

docs: Add Cloudinary to list.md

---

docs/list.md

Add mindsdb to the list.md documentation for swag information.
Fixes #1011 
Thanks for contributing to the [Hacktoberfest Swag List](https://hacktoberfestswaglist.com/) 😃 🎉! Before submitting your pull request, please check off as many of the items below as you can:

docs: Add mindsdb to list.md

---

docs/list.md

DocsGPT added to the Swag List 2025

---

docs/list.md

Added information about .NET Foundation contributions for Hacktoberfest.
This fixes #1024

Update Hacktoberfest Swag-list for .NET Foundation

---

docs/list.md

Added Hyperswitch to Swag List 2025

---

docs/list.md

The first few days of Hacktoberfest are already past, so let's get some more projects on the Swag List!
This adds LambdaTest, Service Now, Interledger, and Modtoberfest.
Closes #1007
Closes #992
Closes #994
Closes #995

Add LambdaTest, Service Now, Interledger, and Modtoberfest

---

docs/list.md

Resolves https://github.com/crweiner/hacktoberfest-swag-list/issues/990 and https://github.com/crweiner/hacktoberfest-swag-list/issues/991

Added Cebu Community & devICT

---

docs/list.md

Tagging @crweiner to take a look. :eyes: 🙌

docs: Add Major League Hacking (MLH) to Hacktoberfest 2025 swag list

---

docs/list.md

docs: Add CopilotKit to the `list.md`
